---
- hosts: all
  roles:
    - role: '{{ playbook_dir }}'
  tasks:
    - command: /usr/local/bin/gh --version
      register: gh_test_output
    - name: gh --version
      debug:
        msg: '{{ gh_test_output.stdout }}'
