---
- name: Testing andrewrothstein.gh
  hosts: all
  tasks:
    - name: Installing andrewrothstein.gh
      ansible.builtin.include_role:
        name: '{{ playbook_dir }}'
    - name: Testing 'gh --version'
      ansible.builtin.command: /usr/local/bin/gh --version
      changed_when: false
      register: gh_test_output
    - name: Output of 'gh --version'
      ansible.builtin.debug:
        msg: '{{ gh_test_output.stdout }}'
