---
- name: Resolve platform specific vars
  ansible.builtin.include_vars: '{{ item }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution }}-{{ ansible_distribution_release }}.yml'
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}.yml'
      skip: true
      paths:
        - '{{ role_path }}/vars'
- name: Look for install at {{ gh_exe }}
  become: true
  ansible.builtin.stat:
    path: '{{ gh_exe }}'
  changed_when: false
  register: gh_binary
- name: Download and install gh
  when: not gh_binary.stat.exists
  block:
    - name: Download {{ gh_url }}
      become: true
      become_user: root
      ansible.builtin.get_url:
        url: '{{ gh_url }}'
        dest: '{{ gh_tmp_archive }}'
        checksum: '{{ gh_checksum }}'
        mode: '644'
    - name: Installing andrewrothstein.unarchivedeps
      ansible.builtin.include_role:
        name: andrewrothstein.unarchivedeps
    - name: Unarchive {{ gh_tmp_archive }}
      become: true
      become_user: root
      ansible.builtin.unarchive:
        remote_src: true
        src: '{{ gh_tmp_archive }}'
        dest: '{{ gh_parent_install_dir }}'
        creates: '{{ gh_install_dir }}'
  always:
    - name: Rm -f {{ gh_tmp_archive }}
      become: true
      become_user: root
      ansible.builtin.file:
        path: '{{ gh_tmp_archive }}'
        state: absent
- name: Linking {{ gh_link }} to {{ gh_exe }}
  become: true
  become_user: root
  ansible.builtin.file:
    src: '{{ gh_exe }}'
    dest: '{{ gh_link }}'
    state: link
